spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://keycloak.local:8080/realms/REALM_SPRING_API
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/barbershop}
    username: ${SPRING_DATASOURCE_USERNAME:postgres}
    password: ${SPRING_DATASOURCE_PASSWORD:1234}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
        default_schema: ${SCHEMA_NAME:control_barbershop}

  sql:
    init:
      mode: always
      encoding: UTF-8

server:
  port: 8081

keycloak-config:
  client-public-key: CLIENT_SPRING