spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://keycloak.barbershop-app.shop:8443/realms/BARBERSHOP
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/barbershop}
    username: ${SPRING_DATASOURCE_USERNAME:postgres}
    password: ${SPRING_DATASOURCE_PASSWORD:1234}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
        default_schema: ${SCHEMA_NAME:control_barbershop}

  sql:
    init:
      mode: always
      encoding: UTF-8

  data:
    redis:
      host: redis.barbershop-app.shop
      port: 6379
      password: "123ateo9"
      timeout: 6000ms
server:
  port: 8081

keycloak-config:
  client-public-key: BARBERSHOP_CLIENT
  internal-url: https://keycloak.barbershop-app.shop:8443